from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('Customer_req', views.Customer_req, name="Customer_req"),
    path('customer/<str:pk>', views.customer_page, name='customer'),
    # path('delete_order/<str:pk>', views.delete_order, name="order"),
    path('add_materials', views.add_materials, name='add_materials'),
    path('update_material', views.update_material, name='update_material'),
    path('get_material/<int:pk>', views.get_material, name='get_material'),
    path('delete_material/<int:pk>/', views.delete_material, name='delete_material'),
    path('alec_api', views.apitest, name='materials'),
    path('list_customers', views.list_customers,name='list_customers'),
    path('create_customer', views.create_customer,name='create_customer'),
    path('update_customer', views.update_customer,name='update_customer'),
    path('get_customer/<int:pk>/', views.get_customer,name='get_customer'),
    # path('delete_customer', views.delete_customer,name='delete_customer'),
    path('list_invoices', views.list_invoices,name='list_invoices'),
    path('create_invoice', views.create_invoice,name='create_invoice'),
    path('get_invoice/<int:pk>/', views.get_invoice,name='get_invoice'),
    path('update_invoice', views.update_invoice,name='update_invoice'),
    path('delete_invoice/<int:pk>/', views.delete_invoice,name='delete_invoice'),
    path('list_suppliers', views.list_suppliers,name='list_suppliers'),
    path('delete_supplier/<int:pk>/', views.delete_supplier,name='delete_supplier'),
    path('create_suppliers', views.create_suppliers,name='create_suppliers'),
    path('get_suppliers/<int:pk>/', views.get_suppliers,name='get_suppliers'),
    path('update_suppliers', views.update_suppliers,name='update_suppliers'),
    path('list_inventorys', views.list_inventorys,name='list_inventorys'),
    path('list_orders', views.list_orders,name='list_orders'),
    path('create_order', views.create_order,name='create_order'),
    path('get_order/<int:pk>/', views.get_order,name='get_order'),
    path('delete_order/<int:pk>/', views.delete_order,name='delete_order'),
    path('update_order', views.update_order,name='update_order'),
    path('list_quotations', views.list_quotations,name='list_quotations'),
    path('create_quotation', views.create_quotation, name='create_quotation'),
    path('get_quotation/<int:pk>/', views.get_quotation, name='get_quotation'),
    path('update_quotation', views.update_quotation, name='update_quotation'),
    path('delete_quotation/<int:pk>/', views.delete_quotation, name='delete_quotation'),
    path('list_revenue', views.list_revenue,name='list_revenue'),
    path('list_demand', views.list_demand,name='list_demand')
    path('list_employees', views.list_employees,name='list_employees'),
    path('create_employees', views.create_employees,name='create_employees'),
    path('update_employees', views.update_employees,name='update_employees'),
    path('get_employees/<int:pk>/', views.get_employees,name='get_employees'),
    path('delete_employees/<int:pk>/', views.delete_employees,name='delete_employees'),

    path('list_salary', views.list_salary,name='list_salary'),
    path('create_salary', views.create_salary,name='create_salary'),
    path('update_salary', views.update_salary,name='update_salary'),
    path('get_salary/<int:pk>/', views.get_salary,name='get_salary'),
    path('delete_salary/<int:pk>/', views.delete_salary,name='delete_salary')
    

]
