# Generated by Django 4.2.4 on 2023-09-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('raw_mat', models.IntegerField()),
            ],
        ),
    ]
