# Generated by Django 4.2.4 on 2023-09-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirements',
            new_name='Customer_req',
        ),
    ]
