# Generated by Django 4.2.4 on 2023-09-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0002_rename_requirements_customer_req'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_req',
            new_name='CustomerRequirements',
        ),
    ]
