# Generated by Django 4.2 on 2023-11-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0003_rename_customer_req_customerrequirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequirements',
            name='raw_mat',
        ),
        migrations.AddField(
            model_name='customerrequirements',
            name='desc',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
