# Generated by Django 4.2 on 2023-11-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0004_remove_customerrequirements_raw_mat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(choices=[('mat1', 'MAT1'), ('mat2', 'MAT2'), ('mat3', 'MAT2'), ('mat4', 'MAT4')], max_length=50, null=True)),
                ('material_amt', models.IntegerField()),
            ],
        ),
    ]
