# Generated by Django 4.2 on 2023-11-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0005_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequirements',
            name='sex',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
