# Generated by Django 4.2 on 2023-11-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0006_customerrequirements_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequirements',
            name='sex',
        ),
    ]
