# Generated by Django 4.2 on 2024-02-29 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0008_customerrequirements_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequirements',
            name='sex',
        ),
        migrations.AddField(
            model_name='customerrequirements',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerrequirements',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
