# Generated by Django 4.2 on 2024-02-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0009_remove_customerrequirements_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequirements',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
