# Generated by Django 4.2 on 2024-02-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0010_customerrequirements_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
