# Generated by Django 4.2 on 2024-03-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0012_customer_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
