# Generated by Django 4.2 on 2024-03-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0016_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
