# Generated by Django 4.2.7 on 2024-03-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0018_customer_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
