# Generated by Django 4.2 on 2024-03-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0025_remove_order_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
