# Generated by Django 4.2 on 2024-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0026_order_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
