# Generated by Django 4.2 on 2024-03-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0027_invoice_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
    ]
