# Generated by Django 4.2 on 2024-03-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0028_remove_invoice_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
