# Generated by Django 4.2 on 2024-03-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0031_invoice_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
