# Generated by Django 4.2 on 2024-03-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0032_invoice_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
    ]
