# Generated by Django 4.2 on 2024-03-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0034_alter_invoice_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('In Progress', 'In Progress')], default='In Progress', max_length=15),
        ),
    ]
