# Generated by Django 4.2 on 2024-03-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0035_invoice_order_status_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotaion_name', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('quotation_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review')], default='Under Review', max_length=15)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabapp.supplier')),
            ],
        ),
    ]
