# Generated by Django 5.0.3 on 2024-03-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0036_supplier_rating_quotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
