# Generated by Django 5.0.3 on 2024-03-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0040_rename_supplier_name_quotation_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
