# Generated by Django 4.2 on 2024-03-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0043_rename_id_supplier_supplier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_id',
            new_name='id',
        ),
    ]
