# Generated by Django 4.2 on 2024-03-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0046_alter_inventory_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='material_amt',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
