# Generated by Django 5.0.2 on 2024-03-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0048_alter_inventory_material_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
