# Generated by Django 4.2.7 on 2024-03-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0051_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date',
            new_name='date_of_joining',
        ),
    ]
