# Generated by Django 4.2.7 on 2024-04-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0052_rename_date_employee_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(),
        ),
    ]
