# Generated by Django 4.2.7 on 2024-04-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabapp', '0054_alter_employee_address_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
